theme: jekyll-theme-midnight
title: "JNVS News"
description: "Your one and only stop for global news."
gitorg: "https://github.com/vardaansinha/stg"
description: "Your one and only stop for global news."
google_analytics:
